// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AssetService 只处理本机文件读取和系统字体枚举，前端负责决定这些资源放到哪个面板。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetSystemFonts(): $CancellablePromise<$models.SystemFont[]> {
    return $Call.ByID(1096140128).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ImportAssets(paths: string[]): $CancellablePromise<$models.AssetBlob[]> {
    return $Call.ByID(300270265, paths).then(($result: any) => {
        return $$createType3($result);
    });
}

export function ImportFonts(paths: string[]): $CancellablePromise<$models.AssetBlob[]> {
    return $Call.ByID(2507223066, paths).then(($result: any) => {
        return $$createType3($result);
    });
}

// Private type creation functions
const $$createType0 = $models.SystemFont.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.AssetBlob.createFrom;
const $$createType3 = $Create.Array($$createType2);
