// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DocumentService 暴露给前端负责 .tnote 的新建、打开和保存；这里不掺入 UI 状态。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetAppDataDir(): $CancellablePromise<string> {
    return $Call.ByID(1080555618);
}

export function NewDocument(): $CancellablePromise<$models.NotePackage> {
    return $Call.ByID(2048312367).then(($result: any) => {
        return $$createType0($result);
    });
}

export function OpenNote(path: string): $CancellablePromise<$models.NotePackage> {
    return $Call.ByID(2262209600, path).then(($result: any) => {
        return $$createType0($result);
    });
}

export function SaveNote(path: string, note: $models.NotePackage): $CancellablePromise<void> {
    return $Call.ByID(3591808041, path, note);
}

// Private type creation functions
const $$createType0 = $models.NotePackage.createFrom;
