// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ExportService 保留只读导出能力，后续若恢复按钮也不需要改动文档保存路径。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ExportPageImage(path: string, dataURL: string): $CancellablePromise<void> {
    return $Call.ByID(3236672827, path, dataURL);
}

export function ExportPortableHTML(path: string, note: $models.NotePackage): $CancellablePromise<void> {
    return $Call.ByID(4244212343, path, note);
}
