// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

export function Frontend(level: string, message: string, fields: { [_ in string]?: any }): $CancellablePromise<void> {
    return $Call.ByID(1337476659, level, message, fields);
}

export function Path(): $CancellablePromise<string> {
    return $Call.ByID(4245591640);
}

export function Paths(): $CancellablePromise<string[]> {
    return $Call.ByID(2297849265).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
