// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AssetBlob {
    /**
     * Path 是 ZIP 包内部相对路径，打开外部 .tnote 时必须经过安全校验后才能读取。
     */
    "id": string;
    "name": string;
    "hash": string;
    "mimeType": string;
    "size": number;
    "path": string;

    /**
     * DataBase64 是跨 Wails 边界传输素材内容的承载字段，保存时会重新写回 ZIP。
     */
    "dataBase64": string;
    "dataUrl"?: string;

    /** Creates a new AssetBlob instance. */
    constructor($$source: Partial<AssetBlob> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("hash" in $$source)) {
            this["hash"] = "";
        }
        if (!("mimeType" in $$source)) {
            this["mimeType"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("dataBase64" in $$source)) {
            this["dataBase64"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AssetBlob instance from a string or object.
     */
    static createFrom($$source: any = {}): AssetBlob {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AssetBlob($$parsedSource as Partial<AssetBlob>);
    }
}

export class AssetMeta {
    /**
     * Path 是 ZIP 包内部相对路径，打开外部 .tnote 时必须经过安全校验后才能读取。
     */
    "id": string;
    "name": string;
    "hash": string;
    "mimeType": string;
    "size": number;
    "path": string;

    /** Creates a new AssetMeta instance. */
    constructor($$source: Partial<AssetMeta> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("hash" in $$source)) {
            this["hash"] = "";
        }
        if (!("mimeType" in $$source)) {
            this["mimeType"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AssetMeta instance from a string or object.
     */
    static createFrom($$source: any = {}): AssetMeta {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AssetMeta($$parsedSource as Partial<AssetMeta>);
    }
}

export class NoteDocument {
    /**
     * Document 是可编辑状态的完整快照；协同时仍以 Yjs update 为事实源。
     */
    "formatVersion": number;
    "title": string;
    "createdAt": string;
    "updatedAt": string;
    "pages": NotePage[];
    "elements": NoteElement[];
    "assets": AssetMeta[];

    /**
     * Stickers 独立于 Assets，避免左侧图片素材栏和右侧贴纸控制面板互相污染。
     */
    "stickers": AssetMeta[];
    "fonts": AssetMeta[];
    "templates": TemplateDef[];

    /** Creates a new NoteDocument instance. */
    constructor($$source: Partial<NoteDocument> = {}) {
        if (!("formatVersion" in $$source)) {
            this["formatVersion"] = 0;
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = "";
        }
        if (!("pages" in $$source)) {
            this["pages"] = [];
        }
        if (!("elements" in $$source)) {
            this["elements"] = [];
        }
        if (!("assets" in $$source)) {
            this["assets"] = [];
        }
        if (!("stickers" in $$source)) {
            this["stickers"] = [];
        }
        if (!("fonts" in $$source)) {
            this["fonts"] = [];
        }
        if (!("templates" in $$source)) {
            this["templates"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NoteDocument instance from a string or object.
     */
    static createFrom($$source: any = {}): NoteDocument {
        const $$createField4_0 = $$createType1;
        const $$createField5_0 = $$createType3;
        const $$createField6_0 = $$createType5;
        const $$createField7_0 = $$createType5;
        const $$createField8_0 = $$createType5;
        const $$createField9_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("pages" in $$parsedSource) {
            $$parsedSource["pages"] = $$createField4_0($$parsedSource["pages"]);
        }
        if ("elements" in $$parsedSource) {
            $$parsedSource["elements"] = $$createField5_0($$parsedSource["elements"]);
        }
        if ("assets" in $$parsedSource) {
            $$parsedSource["assets"] = $$createField6_0($$parsedSource["assets"]);
        }
        if ("stickers" in $$parsedSource) {
            $$parsedSource["stickers"] = $$createField7_0($$parsedSource["stickers"]);
        }
        if ("fonts" in $$parsedSource) {
            $$parsedSource["fonts"] = $$createField8_0($$parsedSource["fonts"]);
        }
        if ("templates" in $$parsedSource) {
            $$parsedSource["templates"] = $$createField9_0($$parsedSource["templates"]);
        }
        return new NoteDocument($$parsedSource as Partial<NoteDocument>);
    }
}

export class NoteElement {
    /**
     * 坐标始终使用页面坐标，不能写入屏幕缩放后的像素值。
     */
    "id": string;
    "pageId": string;
    "type": string;
    "x": number;
    "y": number;
    "width": number;
    "height": number;
    "rotation": number;
    "zIndex": number;
    "content"?: string;
    "assetId"?: string;
    "style"?: { [_ in string]?: any };
    "points"?: number[];

    /** Creates a new NoteElement instance. */
    constructor($$source: Partial<NoteElement> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("pageId" in $$source)) {
            this["pageId"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("x" in $$source)) {
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            this["y"] = 0;
        }
        if (!("width" in $$source)) {
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            this["height"] = 0;
        }
        if (!("rotation" in $$source)) {
            this["rotation"] = 0;
        }
        if (!("zIndex" in $$source)) {
            this["zIndex"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NoteElement instance from a string or object.
     */
    static createFrom($$source: any = {}): NoteElement {
        const $$createField11_0 = $$createType8;
        const $$createField12_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("style" in $$parsedSource) {
            $$parsedSource["style"] = $$createField11_0($$parsedSource["style"]);
        }
        if ("points" in $$parsedSource) {
            $$parsedSource["points"] = $$createField12_0($$parsedSource["points"]);
        }
        return new NoteElement($$parsedSource as Partial<NoteElement>);
    }
}

export class NoteManifest {
    /**
     * FormatVersion 是文件格式版本，不等同于应用版本；结构升级必须靠它触发迁移。
     */
    "formatVersion": number;
    "appVersion": string;
    "title": string;
    "createdAt": string;
    "updatedAt": string;
    "documentPath": string;
    "yjsStatePath": string;
    "assets": AssetMeta[];
    "stickers": AssetMeta[];
    "fonts": AssetMeta[];

    /** Creates a new NoteManifest instance. */
    constructor($$source: Partial<NoteManifest> = {}) {
        if (!("formatVersion" in $$source)) {
            this["formatVersion"] = 0;
        }
        if (!("appVersion" in $$source)) {
            this["appVersion"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = "";
        }
        if (!("documentPath" in $$source)) {
            this["documentPath"] = "";
        }
        if (!("yjsStatePath" in $$source)) {
            this["yjsStatePath"] = "";
        }
        if (!("assets" in $$source)) {
            this["assets"] = [];
        }
        if (!("stickers" in $$source)) {
            this["stickers"] = [];
        }
        if (!("fonts" in $$source)) {
            this["fonts"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NoteManifest instance from a string or object.
     */
    static createFrom($$source: any = {}): NoteManifest {
        const $$createField7_0 = $$createType5;
        const $$createField8_0 = $$createType5;
        const $$createField9_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("assets" in $$parsedSource) {
            $$parsedSource["assets"] = $$createField7_0($$parsedSource["assets"]);
        }
        if ("stickers" in $$parsedSource) {
            $$parsedSource["stickers"] = $$createField8_0($$parsedSource["stickers"]);
        }
        if ("fonts" in $$parsedSource) {
            $$parsedSource["fonts"] = $$createField9_0($$parsedSource["fonts"]);
        }
        return new NoteManifest($$parsedSource as Partial<NoteManifest>);
    }
}

export class NotePackage {
    /**
     * Manifest 是 .tnote 包的索引，前端和后端都先读它来判断版本与资源位置。
     */
    "manifest": NoteManifest;
    "document": NoteDocument;
    "yjsState": string;
    "assets": AssetBlob[];
    "stickers": AssetBlob[];
    "fonts": AssetBlob[];
    "thumbnail": string;
    "warnings"?: ServiceNote[];

    /** Creates a new NotePackage instance. */
    constructor($$source: Partial<NotePackage> = {}) {
        if (!("manifest" in $$source)) {
            this["manifest"] = (new NoteManifest());
        }
        if (!("document" in $$source)) {
            this["document"] = (new NoteDocument());
        }
        if (!("yjsState" in $$source)) {
            this["yjsState"] = "";
        }
        if (!("assets" in $$source)) {
            this["assets"] = [];
        }
        if (!("stickers" in $$source)) {
            this["stickers"] = [];
        }
        if (!("fonts" in $$source)) {
            this["fonts"] = [];
        }
        if (!("thumbnail" in $$source)) {
            this["thumbnail"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NotePackage instance from a string or object.
     */
    static createFrom($$source: any = {}): NotePackage {
        const $$createField0_0 = $$createType10;
        const $$createField1_0 = $$createType11;
        const $$createField3_0 = $$createType13;
        const $$createField4_0 = $$createType13;
        const $$createField5_0 = $$createType13;
        const $$createField7_0 = $$createType15;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("manifest" in $$parsedSource) {
            $$parsedSource["manifest"] = $$createField0_0($$parsedSource["manifest"]);
        }
        if ("document" in $$parsedSource) {
            $$parsedSource["document"] = $$createField1_0($$parsedSource["document"]);
        }
        if ("assets" in $$parsedSource) {
            $$parsedSource["assets"] = $$createField3_0($$parsedSource["assets"]);
        }
        if ("stickers" in $$parsedSource) {
            $$parsedSource["stickers"] = $$createField4_0($$parsedSource["stickers"]);
        }
        if ("fonts" in $$parsedSource) {
            $$parsedSource["fonts"] = $$createField5_0($$parsedSource["fonts"]);
        }
        if ("warnings" in $$parsedSource) {
            $$parsedSource["warnings"] = $$createField7_0($$parsedSource["warnings"]);
        }
        return new NotePackage($$parsedSource as Partial<NotePackage>);
    }
}

export class NotePage {
    /**
     * 页面是画布坐标系的边界，元素坐标都相对这个页面左上角。
     */
    "id": string;
    "title": string;
    "width": number;
    "height": number;
    "background": string;

    /**
     * 背景图字段从 v2 开始使用；图片本体在 assets 目录中，页面只保留引用和裁剪参数。
     */
    "backgroundAssetId"?: string;
    "backgroundFit"?: string;
    "backgroundCropX"?: number | null;
    "backgroundCropY"?: number | null;

    /** Creates a new NotePage instance. */
    constructor($$source: Partial<NotePage> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("width" in $$source)) {
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            this["height"] = 0;
        }
        if (!("background" in $$source)) {
            this["background"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NotePage instance from a string or object.
     */
    static createFrom($$source: any = {}): NotePage {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NotePage($$parsedSource as Partial<NotePage>);
    }
}

export class ServiceNote {
    /**
     * ServiceNote 是非致命问题的提示，例如某个素材在包内丢失。
     */
    "code": string;
    "message": string;

    /** Creates a new ServiceNote instance. */
    constructor($$source: Partial<ServiceNote> = {}) {
        if (!("code" in $$source)) {
            this["code"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServiceNote instance from a string or object.
     */
    static createFrom($$source: any = {}): ServiceNote {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ServiceNote($$parsedSource as Partial<ServiceNote>);
    }
}

export class SystemFont {
    /**
     * Name 是文件名，Family 是供下拉框展示的名称；真正使用时会通过 Path 再导入字体文件。
     */
    "name": string;
    "family": string;
    "path": string;

    /** Creates a new SystemFont instance. */
    constructor($$source: Partial<SystemFont> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("family" in $$source)) {
            this["family"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SystemFont instance from a string or object.
     */
    static createFrom($$source: any = {}): SystemFont {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SystemFont($$parsedSource as Partial<SystemFont>);
    }
}

export class TemplateDef {
    /**
     * 模板字段目前保留为空，避免旧计划中的模板能力影响首版编辑器。
     */
    "id": string;
    "name": string;
    "description": string;
    "page": NotePage;
    "elements": NoteElement[];

    /** Creates a new TemplateDef instance. */
    constructor($$source: Partial<TemplateDef> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("page" in $$source)) {
            this["page"] = (new NotePage());
        }
        if (!("elements" in $$source)) {
            this["elements"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TemplateDef instance from a string or object.
     */
    static createFrom($$source: any = {}): TemplateDef {
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("page" in $$parsedSource) {
            $$parsedSource["page"] = $$createField3_0($$parsedSource["page"]);
        }
        if ("elements" in $$parsedSource) {
            $$parsedSource["elements"] = $$createField4_0($$parsedSource["elements"]);
        }
        return new TemplateDef($$parsedSource as Partial<TemplateDef>);
    }
}

// Private type creation functions
const $$createType0 = NotePage.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = NoteElement.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = AssetMeta.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = TemplateDef.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = $Create.Map($Create.Any, $Create.Any);
const $$createType9 = $Create.Array($Create.Any);
const $$createType10 = NoteManifest.createFrom;
const $$createType11 = NoteDocument.createFrom;
const $$createType12 = AssetBlob.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = ServiceNote.createFrom;
const $$createType15 = $Create.Array($$createType14);
