// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * NotebookService 暴露给前端用于手账本文件管理和首页卡片展示。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function BackupNotebook(id: string, destPath: string): $CancellablePromise<void> {
    return $Call.ByID(856131911, id, destPath);
}

/**
 * ConfirmAppQuit 由前端保存完所有手账本后调用，确认可以退出应用。
 */
export function ConfirmAppQuit(): $CancellablePromise<void> {
    return $Call.ByID(3022659404);
}

export function CreateNotebook(name: string): $CancellablePromise<$models.NotebookMeta> {
    return $Call.ByID(338452749, name).then(($result: any) => {
        return $$createType0($result);
    });
}

export function DeleteNotebook(id: string): $CancellablePromise<void> {
    return $Call.ByID(1780839630, id);
}

export function GetNotebooksDir(): $CancellablePromise<string> {
    return $Call.ByID(2052235529);
}

export function GetStartupFilePath(): $CancellablePromise<string> {
    return $Call.ByID(3197573700);
}

export function ImportNotebook(srcPath: string): $CancellablePromise<$models.NotebookMeta> {
    return $Call.ByID(3094445872, srcPath).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ImportNotebookFromData 从 base64 编码的 .tnote 文件内容导入手账本——用于拖放打开等场景，
 * 此时不依赖文件系统路径（WebView2 不暴露 File.path）。
 */
export function ImportNotebookFromData(dataBase64: string, name: string): $CancellablePromise<$models.NotebookMeta> {
    return $Call.ByID(4254562472, dataBase64, name).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ListNotebooks(): $CancellablePromise<$models.NotebookMeta[]> {
    return $Call.ByID(3870406390).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * OpenFileDirectory 在资源管理器中打开文件所在目录并选中该文件。
 */
export function OpenFileDirectory(path: string): $CancellablePromise<void> {
    return $Call.ByID(4159059853, path);
}

export function OpenNotebook(id: string): $CancellablePromise<$models.NotePackage> {
    return $Call.ByID(929955393, id).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * ReadImageAsDataURL 读取本地图片文件，返回 data URL 供前端直接使用。
 */
export function ReadImageAsDataURL(path: string): $CancellablePromise<string> {
    return $Call.ByID(1011583682, path);
}

export function RegisterExternalNotebook(srcPath: string): $CancellablePromise<$models.NotebookMeta> {
    return $Call.ByID(526952511, srcPath).then(($result: any) => {
        return $$createType0($result);
    });
}

export function RenameNotebook(id: string, newName: string): $CancellablePromise<void> {
    return $Call.ByID(3745787803, id, newName);
}

export function UpdateNotebookCover(id: string, coverData: string): $CancellablePromise<void> {
    return $Call.ByID(443334431, id, coverData);
}

export function UpdateNotebookThumbnail(id: string, coverData: string): $CancellablePromise<void> {
    return $Call.ByID(3588680672, id, coverData);
}

// Private type creation functions
const $$createType0 = $models.NotebookMeta.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.NotePackage.createFrom;
